analyzer:
  errors:
    must_be_immutable: ignore
    overridden_fields: ignore
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    unawaited_futures: true
    avoid_print: false
    parameter_assignments: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_final_parameters: true
    avoid_void_async: true

formatter:
  page_width: 100